export const ACTION_LOGGED_OUT = "LOGGED_OUT";

// get cinema
export const ACTION_GET_CINEMA_STARTED = "GET_CINEMA_STARTED";
export const ACTION_GET_CINEMA_SUCCEEDED = "GET_CINEMA_SUCCEEDED";
export const ACTION_GET_CINEMA_FAILED = "GET_CINEMA_FAILED";

// get city
export const ACTION_GET_CITY_STARTED = "GET_CITY_STARTED";
export const ACTION_GET_CITY_SUCCEEDED = "GET_CITY_SUCCEEDED";
export const ACTION_GET_CITY_FAILED = "GET_CITY_FAILED";

// get movie
export const ACTION_GET_MOVIE_STARTED = "GET_MOVIE_STARTED";
export const ACTION_GET_MOVIE_SUCCEEDED = "GET_MOVIE_SUCCEEDED";
export const ACTION_GET_MOVIE_FAILED = "GET_MOVIE_FAILED";

// get movie tomorrow
export const ACTION_GET_MOVIE_TOMORROW_STARTED = "GET_MOVIE_TOMORROW_STARTED";
export const ACTION_GET_MOVIE_TOMORROW_SUCCEEDED = "GET_MOVIE_TOMORROW_SUCCEEDED";
export const ACTION_GET_MOVIE_TOMORROW_FAILED = "GET_MOVIE_TOMORROW_FAILED";

// get movie soon
export const ACTION_GET_MOVIE_SOON_STARTED = "GET_MOVIE_SOON_STARTED";
export const ACTION_GET_MOVIE_SOON_SUCCEEDED = "GET_MOVIE_SOON_SUCCEEDED";
export const ACTION_GET_MOVIE_SOON_FAILED = "GET_MOVIE_SOON_FAILED";

// get news
export const ACTION_GET_NEWS_STARTED = "GET_NEWS_STARTED";
export const ACTION_GET_NEWS_SUCCEEDED = "GET_NEWS_SUCCEEDED";
export const ACTION_GET_NEWS_FAILED = "GET_NEWS_FAILED";

// get news by id
export const ACTION_GET_NEWS_BY_ID_STARTED = "GET_NEWS_BY_ID_STARTED";
export const ACTION_GET_NEWS_BY_ID_SUCCEEDED = "GET_NEWS_BY_ID_SUCCEEDED";
export const ACTION_GET_NEWS_BY_ID_FAILED = "GET_NEWS_BY_ID_FAILED";

// get city
export const ACTION_GET_SCHEDULE_STARTED = "GET_SCHEDULE_STARTED";
export const ACTION_GET_SCHEDULE_SUCCEEDED = "GET_SCHEDULE_SUCCEEDED";
export const ACTION_GET_SCHEDULE_FAILED = "GET_SCHEDULE_FAILED";

// get city
export const ACTION_GET_PROMOTION_STARTED = "GET_PROMOTION_STARTED";
export const ACTION_GET_PROMOTION_SUCCEEDED = "GET_PROMOTION_SUCCEEDED";
export const ACTION_GET_PROMOTION_FAILED = "GET_PROMOTION_FAILED";