export const ACTION_LOGGED_OUT = "LOGGED_OUT";

// get cinema
export const ACTION_GET_CINEMA_STARTED = "GET_CINEMA_STARTED";
export const ACTION_GET_CINEMA_SUCCEEDED = "GET_CINEMA_SUCCEEDED";
export const ACTION_GET_CINEMA_FAILED = "GET_CINEMA_FAILED";

// get city
export const ACTION_GET_CITY_STARTED = "GET_CITY_STARTED";
export const ACTION_GET_CITY_SUCCEEDED = "GET_CITY_SUCCEEDED";
export const ACTION_GET_CITY_FAILED = "GET_CITY_FAILED";

// get movie
export const ACTION_GET_MOVIE_STARTED = "GET_MOVIE_STARTED";
export const ACTION_GET_MOVIE_SUCCEEDED = "GET_MOVIE_SUCCEEDED";
export const ACTION_GET_MOVIE_FAILED = "GET_MOVIE_FAILED";