export const hallMapData = {
  "HallId":4,
  "HallName":"Зал 5 Dolby Atmos Laser ",
  "SeanceId":496454,
  "SeanceName":"Веном Dolby Atmos",
  "Seats":[
     {
        "Id":1010,
        "RowText":"12",
        "SeatText":"29",
        "GridX":3,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1011,
        "RowText":"11",
        "SeatText":"24",
        "GridX":5,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1012,
        "RowText":"10",
        "SeatText":"24",
        "GridX":5,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1013,
        "RowText":"9",
        "SeatText":"21",
        "GridX":5,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1014,
        "RowText":"8",
        "SeatText":"21",
        "GridX":5,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1015,
        "RowText":"7",
        "SeatText":"21",
        "GridX":5,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1016,
        "RowText":"6",
        "SeatText":"21",
        "GridX":5,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1017,
        "RowText":"5",
        "SeatText":"21",
        "GridX":5,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1018,
        "RowText":"4",
        "SeatText":"21",
        "GridX":5,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1019,
        "RowText":"3",
        "SeatText":"21",
        "GridX":5,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1020,
        "RowText":"2",
        "SeatText":"21",
        "GridX":5,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1021,
        "RowText":"1",
        "SeatText":"19",
        "GridX":5,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1022,
        "RowText":"12",
        "SeatText":"28",
        "GridX":4,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1023,
        "RowText":"11",
        "SeatText":"23",
        "GridX":6,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1024,
        "RowText":"10",
        "SeatText":"23",
        "GridX":6,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1025,
        "RowText":"9",
        "SeatText":"20",
        "GridX":6,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1026,
        "RowText":"8",
        "SeatText":"20",
        "GridX":6,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1027,
        "RowText":"7",
        "SeatText":"20",
        "GridX":6,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1028,
        "RowText":"6",
        "SeatText":"20",
        "GridX":6,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1029,
        "RowText":"5",
        "SeatText":"20",
        "GridX":6,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1030,
        "RowText":"4",
        "SeatText":"20",
        "GridX":6,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1031,
        "RowText":"3",
        "SeatText":"20",
        "GridX":6,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1032,
        "RowText":"2",
        "SeatText":"20",
        "GridX":6,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1033,
        "RowText":"1",
        "SeatText":"18",
        "GridX":6,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1034,
        "RowText":"12",
        "SeatText":"27",
        "GridX":5,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1035,
        "RowText":"11",
        "SeatText":"22",
        "GridX":7,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1036,
        "RowText":"10",
        "SeatText":"22",
        "GridX":7,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1037,
        "RowText":"9",
        "SeatText":"19",
        "GridX":7,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1038,
        "RowText":"8",
        "SeatText":"19",
        "GridX":7,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1039,
        "RowText":"7",
        "SeatText":"19",
        "GridX":7,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1040,
        "RowText":"6",
        "SeatText":"19",
        "GridX":7,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1041,
        "RowText":"5",
        "SeatText":"19",
        "GridX":7,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1042,
        "RowText":"4",
        "SeatText":"19",
        "GridX":7,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1043,
        "RowText":"3",
        "SeatText":"19",
        "GridX":7,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1044,
        "RowText":"2",
        "SeatText":"19",
        "GridX":7,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1045,
        "RowText":"1",
        "SeatText":"17",
        "GridX":7,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1046,
        "RowText":"12",
        "SeatText":"26",
        "GridX":6,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1047,
        "RowText":"11",
        "SeatText":"21",
        "GridX":8,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1048,
        "RowText":"10",
        "SeatText":"21",
        "GridX":8,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1049,
        "RowText":"9",
        "SeatText":"18",
        "GridX":8,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1050,
        "RowText":"8",
        "SeatText":"18",
        "GridX":8,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1051,
        "RowText":"7",
        "SeatText":"18",
        "GridX":8,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1052,
        "RowText":"6",
        "SeatText":"18",
        "GridX":8,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1053,
        "RowText":"5",
        "SeatText":"18",
        "GridX":8,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1054,
        "RowText":"4",
        "SeatText":"18",
        "GridX":8,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1055,
        "RowText":"3",
        "SeatText":"18",
        "GridX":8,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1056,
        "RowText":"2",
        "SeatText":"18",
        "GridX":8,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1057,
        "RowText":"1",
        "SeatText":"16",
        "GridX":8,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1058,
        "RowText":"12",
        "SeatText":"25",
        "GridX":7,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1059,
        "RowText":"11",
        "SeatText":"20",
        "GridX":9,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1060,
        "RowText":"10",
        "SeatText":"20",
        "GridX":9,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1061,
        "RowText":"9",
        "SeatText":"17",
        "GridX":9,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1062,
        "RowText":"8",
        "SeatText":"17",
        "GridX":9,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1063,
        "RowText":"7",
        "SeatText":"17",
        "GridX":9,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1064,
        "RowText":"6",
        "SeatText":"17",
        "GridX":9,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1065,
        "RowText":"5",
        "SeatText":"17",
        "GridX":9,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1066,
        "RowText":"4",
        "SeatText":"17",
        "GridX":9,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1067,
        "RowText":"3",
        "SeatText":"17",
        "GridX":9,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1068,
        "RowText":"2",
        "SeatText":"17",
        "GridX":9,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1069,
        "RowText":"12",
        "SeatText":"24",
        "GridX":8,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1070,
        "RowText":"11",
        "SeatText":"19",
        "GridX":10,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1071,
        "RowText":"10",
        "SeatText":"19",
        "GridX":10,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1072,
        "RowText":"9",
        "SeatText":"16",
        "GridX":10,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1073,
        "RowText":"8",
        "SeatText":"16",
        "GridX":10,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1074,
        "RowText":"7",
        "SeatText":"16",
        "GridX":10,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1075,
        "RowText":"6",
        "SeatText":"16",
        "GridX":10,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1076,
        "RowText":"5",
        "SeatText":"16",
        "GridX":10,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1077,
        "RowText":"4",
        "SeatText":"16",
        "GridX":10,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1078,
        "RowText":"3",
        "SeatText":"16",
        "GridX":10,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1079,
        "RowText":"2",
        "SeatText":"16",
        "GridX":10,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1080,
        "RowText":"1",
        "SeatText":"15",
        "GridX":9,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1081,
        "RowText":"12",
        "SeatText":"23",
        "GridX":9,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1082,
        "RowText":"11",
        "SeatText":"18",
        "GridX":11,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1083,
        "RowText":"10",
        "SeatText":"18",
        "GridX":11,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1084,
        "RowText":"9",
        "SeatText":"15",
        "GridX":11,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1085,
        "RowText":"8",
        "SeatText":"15",
        "GridX":11,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1086,
        "RowText":"7",
        "SeatText":"15",
        "GridX":11,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1087,
        "RowText":"6",
        "SeatText":"15",
        "GridX":11,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1088,
        "RowText":"5",
        "SeatText":"15",
        "GridX":11,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1089,
        "RowText":"4",
        "SeatText":"15",
        "GridX":11,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1090,
        "RowText":"3",
        "SeatText":"15",
        "GridX":11,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1091,
        "RowText":"2",
        "SeatText":"15",
        "GridX":11,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1092,
        "RowText":"1",
        "SeatText":"14и",
        "GridX":11,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1093,
        "RowText":"12",
        "SeatText":"22",
        "GridX":10,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1094,
        "RowText":"11",
        "SeatText":"17",
        "GridX":12,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1095,
        "RowText":"10",
        "SeatText":"17",
        "GridX":12,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1096,
        "RowText":"9",
        "SeatText":"14",
        "GridX":12,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1097,
        "RowText":"8",
        "SeatText":"14",
        "GridX":12,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1098,
        "RowText":"7",
        "SeatText":"14",
        "GridX":12,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1099,
        "RowText":"6",
        "SeatText":"14",
        "GridX":12,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1100,
        "RowText":"5",
        "SeatText":"14",
        "GridX":12,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1101,
        "RowText":"4",
        "SeatText":"14",
        "GridX":12,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1102,
        "RowText":"3",
        "SeatText":"14",
        "GridX":12,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1103,
        "RowText":"2",
        "SeatText":"14",
        "GridX":12,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1104,
        "RowText":"1",
        "SeatText":"13и",
        "GridX":12,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1105,
        "RowText":"12",
        "SeatText":"21",
        "GridX":11,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1106,
        "RowText":"11",
        "SeatText":"16",
        "GridX":13,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1107,
        "RowText":"10",
        "SeatText":"16",
        "GridX":13,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1108,
        "RowText":"9",
        "SeatText":"13",
        "GridX":13,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1109,
        "RowText":"8",
        "SeatText":"13",
        "GridX":13,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1110,
        "RowText":"7",
        "SeatText":"13",
        "GridX":13,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1111,
        "RowText":"6",
        "SeatText":"13",
        "GridX":13,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1112,
        "RowText":"5",
        "SeatText":"13",
        "GridX":13,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1113,
        "RowText":"4",
        "SeatText":"13",
        "GridX":13,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1114,
        "RowText":"3",
        "SeatText":"13",
        "GridX":13,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1115,
        "RowText":"2",
        "SeatText":"13",
        "GridX":13,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1116,
        "RowText":"1",
        "SeatText":"12и",
        "GridX":13,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1117,
        "RowText":"12",
        "SeatText":"20",
        "GridX":12,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1118,
        "RowText":"11",
        "SeatText":"15",
        "GridX":14,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1119,
        "RowText":"10",
        "SeatText":"15",
        "GridX":14,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1120,
        "RowText":"9",
        "SeatText":"12",
        "GridX":14,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1121,
        "RowText":"8",
        "SeatText":"12",
        "GridX":14,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1122,
        "RowText":"7",
        "SeatText":"12",
        "GridX":14,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1123,
        "RowText":"6",
        "SeatText":"12",
        "GridX":14,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1124,
        "RowText":"5",
        "SeatText":"12",
        "GridX":14,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1125,
        "RowText":"4",
        "SeatText":"12",
        "GridX":14,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1126,
        "RowText":"3",
        "SeatText":"12",
        "GridX":14,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1127,
        "RowText":"2",
        "SeatText":"12",
        "GridX":14,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1128,
        "RowText":"1",
        "SeatText":"11",
        "GridX":14,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1129,
        "RowText":"12",
        "SeatText":"19",
        "GridX":13,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1130,
        "RowText":"11",
        "SeatText":"14",
        "GridX":15,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1131,
        "RowText":"10",
        "SeatText":"14",
        "GridX":15,
        "GridY":5,
        "HallId":4,
        "IsFree":false,
        "status":0
     },
     {
        "Id":1132,
        "RowText":"9",
        "SeatText":"11",
        "GridX":15,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1133,
        "RowText":"8",
        "SeatText":"11",
        "GridX":15,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1134,
        "RowText":"7",
        "SeatText":"11",
        "GridX":15,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1135,
        "RowText":"6",
        "SeatText":"11",
        "GridX":15,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1136,
        "RowText":"5",
        "SeatText":"11",
        "GridX":15,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1137,
        "RowText":"4",
        "SeatText":"11",
        "GridX":15,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1138,
        "RowText":"3",
        "SeatText":"11",
        "GridX":15,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1139,
        "RowText":"2",
        "SeatText":"11",
        "GridX":15,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1140,
        "RowText":"1",
        "SeatText":"10",
        "GridX":15,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1141,
        "RowText":"12",
        "SeatText":"18",
        "GridX":14,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1142,
        "RowText":"11",
        "SeatText":"13",
        "GridX":16,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1143,
        "RowText":"10",
        "SeatText":"13",
        "GridX":16,
        "GridY":5,
        "HallId":4,
        "IsFree":false,
        "status":0
     },
     {
        "Id":1144,
        "RowText":"9",
        "SeatText":"10",
        "GridX":16,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1145,
        "RowText":"8",
        "SeatText":"10",
        "GridX":16,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1146,
        "RowText":"7",
        "SeatText":"10",
        "GridX":16,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1147,
        "RowText":"6",
        "SeatText":"10",
        "GridX":16,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1148,
        "RowText":"5",
        "SeatText":"10",
        "GridX":16,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1149,
        "RowText":"4",
        "SeatText":"10",
        "GridX":16,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1150,
        "RowText":"3",
        "SeatText":"10",
        "GridX":16,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1151,
        "RowText":"2",
        "SeatText":"10",
        "GridX":16,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1152,
        "RowText":"1",
        "SeatText":"9",
        "GridX":16,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1153,
        "RowText":"12",
        "SeatText":"17",
        "GridX":15,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1154,
        "RowText":"11",
        "SeatText":"12",
        "GridX":17,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1155,
        "RowText":"10",
        "SeatText":"12",
        "GridX":17,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1156,
        "RowText":"9",
        "SeatText":"9",
        "GridX":17,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1157,
        "RowText":"8",
        "SeatText":"9",
        "GridX":17,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1158,
        "RowText":"7",
        "SeatText":"9",
        "GridX":17,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1159,
        "RowText":"6",
        "SeatText":"9",
        "GridX":17,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1160,
        "RowText":"5",
        "SeatText":"9",
        "GridX":17,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1161,
        "RowText":"4",
        "SeatText":"9",
        "GridX":17,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1162,
        "RowText":"3",
        "SeatText":"9",
        "GridX":17,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1163,
        "RowText":"2",
        "SeatText":"9",
        "GridX":17,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1164,
        "RowText":"1",
        "SeatText":"8",
        "GridX":17,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1165,
        "RowText":"12",
        "SeatText":"16",
        "GridX":16,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1166,
        "RowText":"11",
        "SeatText":"11",
        "GridX":18,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1167,
        "RowText":"10",
        "SeatText":"11",
        "GridX":18,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1168,
        "RowText":"9",
        "SeatText":"8",
        "GridX":18,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1169,
        "RowText":"8",
        "SeatText":"8",
        "GridX":18,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1170,
        "RowText":"7",
        "SeatText":"8",
        "GridX":18,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1171,
        "RowText":"6",
        "SeatText":"8",
        "GridX":18,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1172,
        "RowText":"5",
        "SeatText":"8",
        "GridX":18,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1173,
        "RowText":"4",
        "SeatText":"8",
        "GridX":18,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1174,
        "RowText":"3",
        "SeatText":"8",
        "GridX":18,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1175,
        "RowText":"2",
        "SeatText":"8",
        "GridX":18,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1176,
        "RowText":"1",
        "SeatText":"7и",
        "GridX":18,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1177,
        "RowText":"12",
        "SeatText":"15",
        "GridX":17,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1178,
        "RowText":"11",
        "SeatText":"10",
        "GridX":19,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1179,
        "RowText":"10",
        "SeatText":"10",
        "GridX":19,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1180,
        "RowText":"9",
        "SeatText":"7",
        "GridX":19,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1181,
        "RowText":"8",
        "SeatText":"7",
        "GridX":19,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1182,
        "RowText":"7",
        "SeatText":"7",
        "GridX":19,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1183,
        "RowText":"6",
        "SeatText":"7",
        "GridX":19,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1184,
        "RowText":"5",
        "SeatText":"7",
        "GridX":19,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1185,
        "RowText":"4",
        "SeatText":"7",
        "GridX":19,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1186,
        "RowText":"3",
        "SeatText":"7",
        "GridX":19,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1187,
        "RowText":"2",
        "SeatText":"7",
        "GridX":19,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1188,
        "RowText":"1",
        "SeatText":"6и",
        "GridX":19,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1189,
        "RowText":"12",
        "SeatText":"14",
        "GridX":18,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1190,
        "RowText":"11",
        "SeatText":"9",
        "GridX":20,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1191,
        "RowText":"10",
        "SeatText":"9",
        "GridX":20,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1192,
        "RowText":"9",
        "SeatText":"6",
        "GridX":20,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1193,
        "RowText":"8",
        "SeatText":"6",
        "GridX":20,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1194,
        "RowText":"7",
        "SeatText":"6",
        "GridX":20,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1195,
        "RowText":"6",
        "SeatText":"6",
        "GridX":20,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1196,
        "RowText":"5",
        "SeatText":"6",
        "GridX":20,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1197,
        "RowText":"4",
        "SeatText":"6",
        "GridX":20,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1198,
        "RowText":"3",
        "SeatText":"6",
        "GridX":20,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1199,
        "RowText":"2",
        "SeatText":"6",
        "GridX":20,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1200,
        "RowText":"12",
        "SeatText":"13",
        "GridX":19,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1201,
        "RowText":"11",
        "SeatText":"8",
        "GridX":21,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1202,
        "RowText":"10",
        "SeatText":"8",
        "GridX":21,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1203,
        "RowText":"9",
        "SeatText":"5",
        "GridX":21,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1204,
        "RowText":"8",
        "SeatText":"5",
        "GridX":21,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1205,
        "RowText":"7",
        "SeatText":"5",
        "GridX":21,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1206,
        "RowText":"6",
        "SeatText":"5",
        "GridX":21,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1207,
        "RowText":"5",
        "SeatText":"5",
        "GridX":21,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1208,
        "RowText":"4",
        "SeatText":"5",
        "GridX":21,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1209,
        "RowText":"3",
        "SeatText":"5",
        "GridX":21,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1210,
        "RowText":"2",
        "SeatText":"5",
        "GridX":21,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1211,
        "RowText":"1",
        "SeatText":"5и",
        "GridX":20,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1212,
        "RowText":"12",
        "SeatText":"12",
        "GridX":20,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1213,
        "RowText":"11",
        "SeatText":"7",
        "GridX":22,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1214,
        "RowText":"10",
        "SeatText":"7",
        "GridX":22,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1215,
        "RowText":"9",
        "SeatText":"4",
        "GridX":22,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1216,
        "RowText":"8",
        "SeatText":"4",
        "GridX":22,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1217,
        "RowText":"7",
        "SeatText":"4",
        "GridX":22,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1218,
        "RowText":"6",
        "SeatText":"4",
        "GridX":22,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1219,
        "RowText":"5",
        "SeatText":"4",
        "GridX":22,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1220,
        "RowText":"4",
        "SeatText":"4",
        "GridX":22,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1221,
        "RowText":"3",
        "SeatText":"4",
        "GridX":22,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1222,
        "RowText":"2",
        "SeatText":"4",
        "GridX":22,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1223,
        "RowText":"1",
        "SeatText":"4",
        "GridX":22,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1224,
        "RowText":"12",
        "SeatText":"11",
        "GridX":21,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1225,
        "RowText":"11",
        "SeatText":"6",
        "GridX":23,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1226,
        "RowText":"10",
        "SeatText":"6",
        "GridX":23,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1227,
        "RowText":"9",
        "SeatText":"3",
        "GridX":23,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1228,
        "RowText":"8",
        "SeatText":"3",
        "GridX":23,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1229,
        "RowText":"7",
        "SeatText":"3",
        "GridX":23,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1230,
        "RowText":"6",
        "SeatText":"3",
        "GridX":23,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1231,
        "RowText":"5",
        "SeatText":"3",
        "GridX":23,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1232,
        "RowText":"4",
        "SeatText":"3",
        "GridX":23,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1233,
        "RowText":"3",
        "SeatText":"3",
        "GridX":23,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1234,
        "RowText":"2",
        "SeatText":"3",
        "GridX":23,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1235,
        "RowText":"1",
        "SeatText":"3",
        "GridX":23,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1236,
        "RowText":"12",
        "SeatText":"10",
        "GridX":22,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1237,
        "RowText":"11",
        "SeatText":"5",
        "GridX":24,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1238,
        "RowText":"10",
        "SeatText":"5",
        "GridX":24,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1239,
        "RowText":"9",
        "SeatText":"2",
        "GridX":24,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1240,
        "RowText":"8",
        "SeatText":"2",
        "GridX":24,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1241,
        "RowText":"7",
        "SeatText":"2",
        "GridX":24,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1242,
        "RowText":"6",
        "SeatText":"2",
        "GridX":24,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1243,
        "RowText":"5",
        "SeatText":"2",
        "GridX":24,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1244,
        "RowText":"4",
        "SeatText":"2",
        "GridX":24,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1245,
        "RowText":"3",
        "SeatText":"2",
        "GridX":24,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1246,
        "RowText":"2",
        "SeatText":"2",
        "GridX":24,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1247,
        "RowText":"1",
        "SeatText":"2",
        "GridX":24,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1248,
        "RowText":"12",
        "SeatText":"9",
        "GridX":23,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1249,
        "RowText":"11",
        "SeatText":"4",
        "GridX":25,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1250,
        "RowText":"10",
        "SeatText":"4",
        "GridX":25,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1251,
        "RowText":"9",
        "SeatText":"1",
        "GridX":25,
        "GridY":6,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1252,
        "RowText":"8",
        "SeatText":"1",
        "GridX":25,
        "GridY":7,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1253,
        "RowText":"7",
        "SeatText":"1",
        "GridX":25,
        "GridY":8,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1254,
        "RowText":"6",
        "SeatText":"1",
        "GridX":25,
        "GridY":9,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1255,
        "RowText":"5",
        "SeatText":"1",
        "GridX":25,
        "GridY":10,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1256,
        "RowText":"4",
        "SeatText":"1",
        "GridX":25,
        "GridY":11,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1257,
        "RowText":"3",
        "SeatText":"1",
        "GridX":25,
        "GridY":12,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1258,
        "RowText":"2",
        "SeatText":"1",
        "GridX":25,
        "GridY":13,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1259,
        "RowText":"1",
        "SeatText":"1",
        "GridX":25,
        "GridY":14,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1260,
        "RowText":"12",
        "SeatText":"8",
        "GridX":24,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1261,
        "RowText":"12",
        "SeatText":"7",
        "GridX":25,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1262,
        "RowText":"12",
        "SeatText":"6",
        "GridX":26,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1263,
        "RowText":"12",
        "SeatText":"5",
        "GridX":27,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1264,
        "RowText":"12",
        "SeatText":"4",
        "GridX":28,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1265,
        "RowText":"12",
        "SeatText":"3",
        "GridX":29,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1266,
        "RowText":"11",
        "SeatText":"3",
        "GridX":29,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1267,
        "RowText":"10",
        "SeatText":"3",
        "GridX":29,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1268,
        "RowText":"12",
        "SeatText":"2",
        "GridX":30,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1269,
        "RowText":"11",
        "SeatText":"2",
        "GridX":30,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1270,
        "RowText":"10",
        "SeatText":"2",
        "GridX":30,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1271,
        "RowText":"12",
        "SeatText":"1",
        "GridX":31,
        "GridY":3,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1272,
        "RowText":"11",
        "SeatText":"1",
        "GridX":31,
        "GridY":4,
        "HallId":4,
        "IsFree":true,
        "status":1
     },
     {
        "Id":1273,
        "RowText":"10",
        "SeatText":"1",
        "GridX":31,
        "GridY":5,
        "HallId":4,
        "IsFree":true,
        "status":1
     }
  ]
}